// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbufahmyresaiiljunnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idWZhaG15cmVzYWlpbGp1bm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzAxMzcsImV4cCI6MjA3NDM0NjEzN30.wJnYIFu8dtgdn6H9QmvL3NHO80EocBEHNQ_DicDtwTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});